# Test

GET http://localhost:5000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQ0MzEwMDAwLCJleHAiOjE3NDQzMTcyMDB9.6qzZBPRSJy0uuDdQNsNjA3B7A3l8Fn1GGZJPluL1u8Q

###
# Auth

POST http://localhost:5000/auth/signup
Content-Type: application/json

{
	"email": "hi.there@gmail.com",
	"password": "test123"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
	"email": "hi.there@gmail.com",
	"password": "test123"
}

###

POST http://localhost:5000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQ0MzEwMDAwLCJleHAiOjE3NDQzMTcyMDB9.6qzZBPRSJy0uuDdQNsNjA3B7A3l8Fn1GGZJPluL1u8Q

###
POST http://localhost:5000/auth/invalidate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQ0MzEwMDAwLCJleHAiOjE3NDQzMTcyMDB9.6qzZBPRSJy0uuDdQNsNjA3B7A3l8Fn1GGZJPluL1u8Q

###
# Posts

GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQzNzcyMDEwLCJleHAiOjE3NDM3NzkyMTB9.OhB1EMtudWDLORU5btRF6KVrnt6Bfanz4O9O6go4OHs
