GET http://localhost:5000/
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQzNzYwMDE1LCJleHAiOjE3NDM3NjAwMzV9.Gd-VGSFmYr1sfRVK8TytWao8snTTxh4O_silweTPPlY

###

POST http://localhost:5000/auth/signup
Content-Type: application/json

{
	"email": "hi.there@gmail.com",
	"password": "test123"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
	"email": "hi.there@gmail.com",
	"password": "test123"
}

###

POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQzNzU5OTc4fQ.LczdI-zcCDGsabJmWNyh_aaTtLHEQ5fs4QTDfy-4eB8"
}

###
POST http://localhost:5000/auth/invalidate
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQzNzYwMjMzfQ.Ag77XvZrd4OQRWVQyZP1adikiVQsM8Xne29BJhL4ISE"
}