GET http://localhost:5000/
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQzNzY4NjAyLCJleHAiOjE3NDM3Njg2MjJ9.JK52WgNBB3RcJdBFrbhW6VmtjSNRRCkAfpbBCZzez0M

###

POST http://localhost:5000/auth/signup
Content-Type: application/json

{
	"email": "hi.there@gmail.com",
	"password": "test123"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
	"email": "hi.there@gmail.com",
	"password": "test123"
}

###

POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQzNzY4NTc4fQ.RwR1yX7O1bAE2yncfHeaSIshTX_JyVcxOfO1_dyx3ds"
}

###
POST http://localhost:5000/auth/invalidate
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsImVtYWlsIjoiaGkudGhlcmVAZ21haWwuY29tIiwiaWF0IjoxNzQzNzYxMzU0fQ.sgtjJlc46Z4DKw79rBhL_hvaJ_mwodc5ao1CPNaFZGc"
}